apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: manuweblb1
  name: manuweblb1
  namespace: manu-ns
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: manuwebapp
  type: NodePort
status:
  loadBalancer: {}
